spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.227.202:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 964660633Cm.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



